Embed setup_python shell script to fix file not found error

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -38,7 +38,7 @@ runs:
         lzma lzma-dev tk-dev uuid-dev zlib1g-dev
       shell: bash
 
-    - name: Install Python with Debug
+    - name: Build Python with Debug
       if: steps.cache-python.outputs.cache-hit != 'true'
       run: |
         cd ${{ runner.workspace }}/dl
@@ -47,17 +47,76 @@ runs:
         ./configure --with-pydebug --prefix=$RUNNER_TEMP/Python/ && make -j && make install
       shell: bash
 
-    - name: Copy Python Debug Module to Cache
+    - name: Copy Python gdb Module to Cache
       if: steps.cache-python.outputs.cache-hit != 'true'
       run: |
         cp ${{ runner.workspace }}/dl/Python-${{ inputs.python-version }}/python-gdb.py $RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/
       shell: bash
 
-    - name: Install Python
+    - name: Install Python in the Runner Tools
       if: steps.cache-python.outputs.cache-hit != 'true'
       run: |
-        sed -i 's/{{__VERSION_FULL__}}/${{ inputs.python-version }}/' setup_debug_python.sh
-        setup_debug_python.sh
+        # https://github.com/actions/python-versions/
+        # MIT License
+        # Copyright (c) 2020 GitHub
+
+        set -e
+
+        PYTHON_FULL_VERSION=${{ inputs.python-version }}
+        MAJOR_VERSION=$(echo $PYTHON_FULL_VERSION | cut -d '.' -f 1)
+        MINOR_VERSION=$(echo $PYTHON_FULL_VERSION | cut -d '.' -f 2)
+
+        PYTHON_MAJOR=python$MAJOR_VERSION
+        PYTHON_MAJOR_DOT_MINOR=python$MAJOR_VERSION.$MINOR_VERSION
+        PYTHON_MAJORMINOR=python$MAJOR_VERSION$MINOR_VERSION
+
+        if [ -z ${AGENT_TOOLSDIRECTORY+x} ]; then
+        # No AGENT_TOOLSDIRECTORY on GitHub images
+        TOOLCACHE_ROOT=$RUNNER_TOOL_CACHE
+        else
+        TOOLCACHE_ROOT=$AGENT_TOOLSDIRECTORY
+        fi
+
+        PYTHON_TOOLCACHE_PATH=$TOOLCACHE_ROOT/Python
+        PYTHON_TOOLCACHE_VERSION_PATH=$PYTHON_TOOLCACHE_PATH/$PYTHON_FULL_VERSION
+        PYTHON_TOOLCACHE_VERSION_ARCH_PATH=$PYTHON_TOOLCACHE_VERSION_PATH/x64
+
+        echo "Check if Python hostedtoolcache folder exist..."
+        if [ ! -d $PYTHON_TOOLCACHE_PATH ]; then
+        echo "Creating Python hostedtoolcache folder..."
+        mkdir -p $PYTHON_TOOLCACHE_PATH
+        elif [ -d $PYTHON_TOOLCACHE_VERSION_PATH ]; then
+        echo "Deleting Python $PYTHON_FULL_VERSION"
+        rm -rf $PYTHON_TOOLCACHE_VERSION_PATH
+        fi
+
+        echo "Create Python $PYTHON_FULL_VERSION folder"
+        mkdir -p $PYTHON_TOOLCACHE_VERSION_ARCH_PATH
+
+        echo "Copy Python binaries to hostedtoolcache folder"
+        cd $RUNNER_TEMP/Python
+        cp -R ./* $PYTHON_TOOLCACHE_VERSION_ARCH_PATH
+        # rm $PYTHON_TOOLCACHE_VERSION_ARCH_PATH/setup.sh
+
+        cd $PYTHON_TOOLCACHE_VERSION_ARCH_PATH
+
+        echo "Create additional symlinks (Required for the UsePythonVersion Azure Pipelines task and the setup-python GitHub Action)"
+        ln -s ./bin/$PYTHON_MAJOR_DOT_MINOR python
+
+        cd bin/
+        ln -s $PYTHON_MAJOR_DOT_MINOR $PYTHON_MAJORMINOR
+        if [ ! -f python ]; then
+        ln -s $PYTHON_MAJOR_DOT_MINOR python
+        fi
+
+        chmod +x ../python $PYTHON_MAJOR $PYTHON_MAJOR_DOT_MINOR $PYTHON_MAJORMINOR python
+
+        echo "Upgrading PIP..."
+        ./python -m ensurepip
+        ./python -m pip install --ignore-installed pip --no-warn-script-location
+
+        echo "Create complete file"
+        touch $PYTHON_TOOLCACHE_VERSION_PATH/x64.complete
       shell: bash
 
     - name: Add Python to path
@@ -67,7 +126,7 @@ runs:
         echo "$GITHUB_PATH"
       shell: bash
 
-    - name: Copy Python Debug Module to Workspace and Add to GDB
+    - name: Copy Python gdb Module to Workspace and Add to gdbinit
       if: steps.cache-python.outputs.cache-hit != 'true'
       run: |
         cp $RUNNER_TOOL_CACHE/Python/${{ inputs.python-version }}/python-gdb.py $GITHUB_WORKSPACE/
